package com.sgarsgaya.codeatlas.core.model;

public enum NodeKind {

    // Code
    REPOSITORY, GRADLE_MODULE, SOURCE_SET, FILE, PACKAGE,
    CLASS, INTERFACE, ENUM, METHOD, FIELD,
    CONSTRUCTOR, ANNOTATION, TEST,

    // Spring
    SPRING_BEAN, CONTROLLER, SERVICE, REPOSITORY_BEAN,
    CONFIGURATION_CLASS, BEAN_PROVIDER_METHOD, SCHEDULED_JOB,
    TRANSACTION_BOUNDARY, QUALIFIER, PROFILE, CONDITIONAL_BEAN,

    // API
    HTTP_ENDPOINT, OPENAPI_OPERATION, REQUEST_SCHEMA, RESPONSE_SCHEMA,
    SECURITY_REQUIREMENT, ERROR_RESPONSE,

    // Data
    ENTITY, TABLE, REPOSITORY_METHOD, MAPPER, DTO,
    DATABASE_WRITE, DATABASE_READ,

    // External and capability
    EXTERNAL_SERVICE, SERVICE_CLIENT_ARTIFACT, SERVICE_CLIENT_CLASS,
    CLIENT_METHOD, CLIENT_BEAN, REMOTE_ENDPOINT,
    BUSINESS_CAPABILITY, CAPABILITY_EVIDENCE
}
