spring:
  datasource:
    url: jdbc:h2:file:./.repoatlas/local-db/codeatlas;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

atlas:
  app-name: codeatlas-local
